package com.kofax.mobile.sdk._internal.impl.extraction.onDevice;

import java.util.HashMap;
import java.util.Map;

/* renamed from: com.kofax.mobile.sdk._internal.impl.extraction.onDevice.g */
public class C8143g {

    /* renamed from: Lk */
    private static final Map<String, String> f4165Lk;

    static {
        HashMap hashMap = new HashMap();
        f4165Lk = hashMap;
        hashMap.put("ABW", "Aruba");
        f4165Lk.put("AFG", "Afghanistan");
        f4165Lk.put("AGO", "Angola");
        f4165Lk.put("AIA", "Anguilla");
        f4165Lk.put("ALA", "Åland Islands");
        f4165Lk.put("ALB", "Albania");
        f4165Lk.put("AND", "Andorra");
        f4165Lk.put("ARE", "United Arab Emirates");
        f4165Lk.put("ARG", "Argentina");
        f4165Lk.put("ARM", "Armenia");
        f4165Lk.put("ASM", "American Samoa");
        f4165Lk.put("ATA", "Antarctica");
        f4165Lk.put("ATF", "French Southern Territories");
        f4165Lk.put("ATG", "Antigua and Barbuda");
        f4165Lk.put("AUS", "Australia");
        f4165Lk.put("AUT", "Austria");
        f4165Lk.put("AZE", "Azerbaijan");
        f4165Lk.put("BDI", "Burundi");
        f4165Lk.put("BEL", "Belgium");
        f4165Lk.put("BEN", "Benin");
        f4165Lk.put("BES", "Bonaire, Sint Eustatius and Saba");
        f4165Lk.put("BFA", "Burkina Faso");
        f4165Lk.put("BGD", "Bangladesh");
        f4165Lk.put("BGR", "Bulgaria");
        f4165Lk.put("BHR", "Bahrain");
        f4165Lk.put("BHS", "Bahamas");
        f4165Lk.put("BIH", "Bosnia and Herzegovina");
        f4165Lk.put("BLM", "Saint Barthélemy");
        f4165Lk.put("BLR", "Belarus");
        f4165Lk.put("BLZ", "Belize");
        f4165Lk.put("BMU", "Bermuda");
        f4165Lk.put("BOL", "Bolivia, Plurinational State of");
        f4165Lk.put("BRA", "Brazil");
        f4165Lk.put("BRB", "Barbados");
        f4165Lk.put("BRN", "Brunei Darussalam");
        f4165Lk.put("BTN", "Bhutan");
        f4165Lk.put("BVT", "Bouvet Island");
        f4165Lk.put("BWA", "Botswana");
        f4165Lk.put("CAF", "Central African Republic");
        f4165Lk.put("CAN", "Canada");
        f4165Lk.put("CCK", "Cocos (Keeling) Islands");
        f4165Lk.put("CHE", "Switzerland");
        f4165Lk.put("CHL", "Chile");
        f4165Lk.put("CHN", "China");
        f4165Lk.put("CIV", "Côte d'Ivoire");
        f4165Lk.put("CMR", "Cameroon");
        f4165Lk.put("COD", "Congo, the Democratic Republic of the");
        f4165Lk.put("COG", "Congo");
        f4165Lk.put("COK", "Cook Islands");
        f4165Lk.put("COL", "Colombia");
        f4165Lk.put("COM", "Comoros");
        f4165Lk.put("CPV", "Cabo Verde");
        f4165Lk.put("CRI", "Costa Rica");
        f4165Lk.put("CUB", "Cuba");
        f4165Lk.put("CUW", "Curaçao");
        f4165Lk.put("CXR", "Christmas Island");
        f4165Lk.put("CYM", "Cayman Islands");
        f4165Lk.put("CYP", "Cyprus");
        f4165Lk.put("CZE", "Czechia");
        f4165Lk.put("DEU", "Germany");
        f4165Lk.put("DJI", "Djibouti");
        f4165Lk.put("DMA", "Dominica");
        f4165Lk.put("DNK", "Denmark");
        f4165Lk.put("DOM", "Dominican Republic");
        f4165Lk.put("DZA", "Algeria");
        f4165Lk.put("ECU", "Ecuador");
        f4165Lk.put("EGY", "Egypt");
        f4165Lk.put("ERI", "Eritrea");
        f4165Lk.put("ESH", "Western Sahara");
        f4165Lk.put("ESP", "Spain");
        f4165Lk.put("EST", "Estonia");
        f4165Lk.put("ETH", "Ethiopia");
        f4165Lk.put("FIN", "Finland");
        f4165Lk.put("FJI", "Fiji");
        f4165Lk.put("FLK", "Falkland Islands (Malvinas)");
        f4165Lk.put("FRA", "France");
        f4165Lk.put("FRO", "Faroe Islands");
        f4165Lk.put("FSM", "Micronesia, Federated States of");
        f4165Lk.put("GAB", "Gabon");
        f4165Lk.put("GBR", "United Kingdom");
        f4165Lk.put("GEO", "Georgia");
        f4165Lk.put("GGY", "Guernsey");
        f4165Lk.put("GHA", "Ghana");
        f4165Lk.put("GIB", "Gibraltar");
        f4165Lk.put("GIN", "Guinea");
        f4165Lk.put("GLP", "Guadeloupe");
        f4165Lk.put("GMB", "Gambia");
        f4165Lk.put("GNB", "Guinea-Bissau");
        f4165Lk.put("GNQ", "Equatorial Guinea");
        f4165Lk.put("GRC", "Greece");
        f4165Lk.put("GRD", "Grenada");
        f4165Lk.put("GRL", "Greenland");
        f4165Lk.put("GTM", "Guatemala");
        f4165Lk.put("GUF", "French Guiana");
        f4165Lk.put("GUM", "Guam");
        f4165Lk.put("GUY", "Guyana");
        f4165Lk.put("HKG", "Hong Kong");
        f4165Lk.put("HMD", "Heard Island and McDonald Islands");
        f4165Lk.put("HND", "Honduras");
        f4165Lk.put("HRV", "Croatia");
        f4165Lk.put("HTI", "Haiti");
        f4165Lk.put("HUN", "Hungary");
        f4165Lk.put("IDN", "Indonesia");
        f4165Lk.put("IMN", "Isle of Man");
        f4165Lk.put("IND", "India");
        f4165Lk.put("IOT", "British Indian Ocean Territory");
        f4165Lk.put("IRL", "Ireland");
        f4165Lk.put("IRN", "Iran, Islamic Republic of");
        f4165Lk.put("IRQ", "Iraq");
        f4165Lk.put("ISL", "Iceland");
        f4165Lk.put("ISR", "Israel");
        f4165Lk.put("ITA", "Italy");
        f4165Lk.put("JAM", "Jamaica");
        f4165Lk.put("JEY", "Jersey");
        f4165Lk.put("JOR", "Jordan");
        f4165Lk.put("JPN", "Japan");
        f4165Lk.put("KAZ", "Kazakhstan");
        f4165Lk.put("KEN", "Kenya");
        f4165Lk.put("KGZ", "Kyrgyzstan");
        f4165Lk.put("KHM", "Cambodia");
        f4165Lk.put("KIR", "Kiribati");
        f4165Lk.put("KNA", "Saint Kitts and Nevis");
        f4165Lk.put("KOR", "Korea, Republic of");
        f4165Lk.put("KWT", "Kuwait");
        f4165Lk.put("LAO", "Lao People's Democratic Republic");
        f4165Lk.put("LBN", "Lebanon");
        f4165Lk.put("LBR", "Liberia");
        f4165Lk.put("LBY", "Libya");
        f4165Lk.put("LCA", "Saint Lucia");
        f4165Lk.put("LIE", "Liechtenstein");
        f4165Lk.put("LKA", "Sri Lanka");
        f4165Lk.put("LSO", "Lesotho");
        f4165Lk.put("LTU", "Lithuania");
        f4165Lk.put("LUX", "Luxembourg");
        f4165Lk.put("LVA", "Latvia");
        f4165Lk.put("MAC", "Macao");
        f4165Lk.put("MAF", "Saint Martin (French part)");
        f4165Lk.put("MAR", "Morocco");
        f4165Lk.put("MCO", "Monaco");
        f4165Lk.put("MDA", "Moldova, Republic of");
        f4165Lk.put("MDG", "Madagascar");
        f4165Lk.put("MDV", "Maldives");
        f4165Lk.put("MEX", "Mexico");
        f4165Lk.put("MHL", "Marshall Islands");
        f4165Lk.put("MKD", "Macedonia, the former Yugoslav Republic of");
        f4165Lk.put("MLI", "Mali");
        f4165Lk.put("MLT", "Malta");
        f4165Lk.put("MMR", "Myanmar");
        f4165Lk.put("MNE", "Montenegro");
        f4165Lk.put("MNG", "Mongolia");
        f4165Lk.put("MNP", "Northern Mariana Islands");
        f4165Lk.put("MOZ", "Mozambique");
        f4165Lk.put("MRT", "Mauritania");
        f4165Lk.put("MSR", "Montserrat");
        f4165Lk.put("MTQ", "Martinique");
        f4165Lk.put("MUS", "Mauritius");
        f4165Lk.put("MWI", "Malawi");
        f4165Lk.put("MYS", "Malaysia");
        f4165Lk.put("MYT", "Mayotte");
        f4165Lk.put("NAM", "Namibia");
        f4165Lk.put("NCL", "New Caledonia");
        f4165Lk.put("NER", "Niger");
        f4165Lk.put("NFK", "Norfolk Island");
        f4165Lk.put("NGA", "Nigeria");
        f4165Lk.put("NIC", "Nicaragua");
        f4165Lk.put("NIU", "Niue");
        f4165Lk.put("NLD", "Netherlands");
        f4165Lk.put("NOR", "Norway");
        f4165Lk.put("NPL", "Nepal");
        f4165Lk.put("NRU", "Nauru");
        f4165Lk.put("NZL", "New Zealand");
        f4165Lk.put("OMN", "Oman");
        f4165Lk.put("PAK", "Pakistan");
        f4165Lk.put("PAN", "Panama");
        f4165Lk.put("PCN", "Pitcairn");
        f4165Lk.put("PER", "Peru");
        f4165Lk.put("PHL", "Philippines");
        f4165Lk.put("PLW", "Palau");
        f4165Lk.put("PNG", "Papua New Guinea");
        f4165Lk.put("POL", "Poland");
        f4165Lk.put("PRI", "Puerto Rico");
        f4165Lk.put("PRK", "Korea, Democratic People's Republic of");
        f4165Lk.put("PRT", "Portugal");
        f4165Lk.put("PRY", "Paraguay");
        f4165Lk.put("PSE", "Palestine, State of");
        f4165Lk.put("PYF", "French Polynesia");
        f4165Lk.put("QAT", "Qatar");
        f4165Lk.put("REU", "Réunion");
        f4165Lk.put("ROU", "Romania");
        f4165Lk.put("RUS", "Russian Federation");
        f4165Lk.put("RWA", "Rwanda");
        f4165Lk.put("SAU", "Saudi Arabia");
        f4165Lk.put("SDN", "Sudan");
        f4165Lk.put("SEN", "Senegal");
        f4165Lk.put("SGP", "Singapore");
        f4165Lk.put("SGS", "South Georgia and the South Sandwich Islands");
        f4165Lk.put("SHN", "Saint Helena, Ascension and Tristan da Cunha");
        f4165Lk.put("SJM", "Svalbard and Jan Mayen");
        f4165Lk.put("SLB", "Solomon Islands");
        f4165Lk.put("SLE", "Sierra Leone");
        f4165Lk.put("SLV", "El Salvador");
        f4165Lk.put("SMR", "San Marino");
        f4165Lk.put("SOM", "Somalia");
        f4165Lk.put("SPM", "Saint Pierre and Miquelon");
        f4165Lk.put("SRB", "Serbia");
        f4165Lk.put("SSD", "South Sudan");
        f4165Lk.put("STP", "Sao Tome and Principe");
        f4165Lk.put("SUR", "Suriname");
        f4165Lk.put("SVK", "Slovakia");
        f4165Lk.put("SVN", "Slovenia");
        f4165Lk.put("SWE", "Sweden");
        f4165Lk.put("SWZ", "Swaziland");
        f4165Lk.put("SXM", "Sint Maarten (Dutch part)");
        f4165Lk.put("SYC", "Seychelles");
        f4165Lk.put("SYR", "Syrian Arab Republic");
        f4165Lk.put("TCA", "Turks and Caicos Islands");
        f4165Lk.put("TCD", "Chad");
        f4165Lk.put("TGO", "Togo");
        f4165Lk.put("THA", "Thailand");
        f4165Lk.put("TJK", "Tajikistan");
        f4165Lk.put("TKL", "Tokelau");
        f4165Lk.put("TKM", "Turkmenistan");
        f4165Lk.put("TLS", "Timor-Leste");
        f4165Lk.put("TON", "Tonga");
        f4165Lk.put("TTO", "Trinidad and Tobago");
        f4165Lk.put("TUN", "Tunisia");
        f4165Lk.put("TUR", "Turkey");
        f4165Lk.put("TUV", "Tuvalu");
        f4165Lk.put("TWN", "Taiwan, Province of China");
        f4165Lk.put("TZA", "Tanzania, United Republic of");
        f4165Lk.put("UGA", "Uganda");
        f4165Lk.put("UKR", "Ukraine");
        f4165Lk.put("UMI", "United States Minor Outlying Islands");
        f4165Lk.put("URY", "Uruguay");
        f4165Lk.put("USA", "United States");
        f4165Lk.put("UZB", "Uzbekistan");
        f4165Lk.put("VAT", "Holy See (Vatican City State)");
        f4165Lk.put("VCT", "Saint Vincent and the Grenadines");
        f4165Lk.put("VEN", "Venezuela, Bolivarian Republic of");
        f4165Lk.put("VGB", "Virgin Islands, British");
        f4165Lk.put("VIR", "Virgin Islands, U.S.");
        f4165Lk.put("VNM", "Viet Nam");
        f4165Lk.put("VUT", "Vanuatu");
        f4165Lk.put("WLF", "Wallis and Futuna");
        f4165Lk.put("WSM", "Samoa");
        f4165Lk.put("YEM", "Yemen");
        f4165Lk.put("ZAF", "South Africa");
        f4165Lk.put("ZMB", "Zambia");
        f4165Lk.put("ZWE", "Zimbabwe");
    }

    public static String getName(String str) {
        return f4165Lk.get(str);
    }
}
