package com.scb.phone.view.activity.hml;

import android.view.View;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.ImageView;
import android.widget.Space;
import android.widget.TextView;
import androidx.constraintlayout.widget.Group;
import com.scb.phone.R;
import com.scb.phone.view.activity.BaseActivity_ViewBinding;
import com.scb.phone.view.custom.common.CustomAcceptDeclineButtons;
import com.scb.phone.view.custom.common.ProgressStateBar;
import com.scb.phone.view.custom.tierpricing.TierPricingSimplePromotionView;
import p040o.onStart;

public class HmlBaseReviewActivity_ViewBinding extends BaseActivity_ViewBinding {
    private HmlBaseReviewActivity MediaBrowserCompat$ItemReceiver;

    public HmlBaseReviewActivity_ViewBinding(HmlBaseReviewActivity hmlBaseReviewActivity, View view) {
        super(hmlBaseReviewActivity, view);
        this.MediaBrowserCompat$ItemReceiver = hmlBaseReviewActivity;
        hmlBaseReviewActivity.breadcrumbs = (ProgressStateBar) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.psb_review_breadcrumbs, "field 'breadcrumbs'", ProgressStateBar.class);
        hmlBaseReviewActivity.separatorBreadcrumbs = onStart.IconCompatParcelizer(view, R.id.vw_separator_breadcrumbs, "field 'separatorBreadcrumbs'");
        hmlBaseReviewActivity.tvRequestedLoan = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_requested_loan, "field 'tvRequestedLoan'", TextView.class);
        hmlBaseReviewActivity.tierPricingPromo = (TierPricingSimplePromotionView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tpspv_tierpricing_promo, "field 'tierPricingPromo'", TierPricingSimplePromotionView.class);
        hmlBaseReviewActivity.promoSeparator = onStart.IconCompatParcelizer(view, R.id.vw_separator_promo, "field 'promoSeparator'");
        hmlBaseReviewActivity.tvRepaymentAmount = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_repayment_amount, "field 'tvRepaymentAmount'", TextView.class);
        hmlBaseReviewActivity.tvDuration = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_duration, "field 'tvDuration'", TextView.class);
        hmlBaseReviewActivity.tvDurationDescription = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_duration_description, "field 'tvDurationDescription'", TextView.class);
        hmlBaseReviewActivity.tvStartPaymentDate = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_start_payment, "field 'tvStartPaymentDate'", TextView.class);
        hmlBaseReviewActivity.tvTitleLabel = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_title_label, "field 'tvTitleLabel'", TextView.class);
        hmlBaseReviewActivity.tvTitle = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_title, "field 'tvTitle'", TextView.class);
        hmlBaseReviewActivity.tvNameLabel = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_name_label, "field 'tvNameLabel'", TextView.class);
        hmlBaseReviewActivity.tvName = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_name, "field 'tvName'", TextView.class);
        hmlBaseReviewActivity.tvEngNameLabel = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_eng_name_label, "field 'tvEngNameLabel'", TextView.class);
        hmlBaseReviewActivity.tvEngName = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_eng_name, "field 'tvEngName'", TextView.class);
        hmlBaseReviewActivity.tvBirthLabel = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_date_birth_label, "field 'tvBirthLabel'", TextView.class);
        hmlBaseReviewActivity.tvBirth = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_date_birth, "field 'tvBirth'", TextView.class);
        hmlBaseReviewActivity.tvMarital = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_marital, "field 'tvMarital'", TextView.class);
        hmlBaseReviewActivity.tvEducation = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_education, "field 'tvEducation'", TextView.class);
        hmlBaseReviewActivity.tvResidential = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_residential, "field 'tvResidential'", TextView.class);
        hmlBaseReviewActivity.tvNationalIdLabel = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_national_id_label, "field 'tvNationalIdLabel'", TextView.class);
        hmlBaseReviewActivity.tvNationalId = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_national_id, "field 'tvNationalId'", TextView.class);
        hmlBaseReviewActivity.tvLaserIdLabel = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_laser_id_label, "field 'tvLaserIdLabel'", TextView.class);
        hmlBaseReviewActivity.tvLaserId = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_laser_id, "field 'tvLaserId'", TextView.class);
        hmlBaseReviewActivity.tvIssueLabel = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_issue_label, "field 'tvIssueLabel'", TextView.class);
        hmlBaseReviewActivity.tvIssue = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_issue, "field 'tvIssue'", TextView.class);
        hmlBaseReviewActivity.tvExpiry = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_expiry, "field 'tvExpiry'", TextView.class);
        hmlBaseReviewActivity.tvLaserLabel = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_laser_label, "field 'tvLaserLabel'", TextView.class);
        hmlBaseReviewActivity.tvLaser = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_laser, "field 'tvLaser'", TextView.class);
        hmlBaseReviewActivity.tvMobileNumber = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_mobile, "field 'tvMobileNumber'", TextView.class);
        hmlBaseReviewActivity.tvEmail = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_email, "field 'tvEmail'", TextView.class);
        hmlBaseReviewActivity.tvHomeAddressLabel = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_home_address_label, "field 'tvHomeAddressLabel'", TextView.class);
        hmlBaseReviewActivity.tvHomeAddress = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_home_address, "field 'tvHomeAddress'", TextView.class);
        hmlBaseReviewActivity.tvMailingAddress = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_mailing_address, "field 'tvMailingAddress'", TextView.class);
        hmlBaseReviewActivity.tvMonthlyIncome = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_monthly_income, "field 'tvMonthlyIncome'", TextView.class);
        hmlBaseReviewActivity.ivPhotoAttached = (ImageView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.iv_photo_attached, "field 'ivPhotoAttached'", ImageView.class);
        hmlBaseReviewActivity.grRequiredDocuments = onStart.IconCompatParcelizer(view, R.id.cs_layout_photos_attached, "field 'grRequiredDocuments'");
        hmlBaseReviewActivity.tvPhotoAttached = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_photo_attached, "field 'tvPhotoAttached'", TextView.class);
        hmlBaseReviewActivity.tvJob = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_job, "field 'tvJob'", TextView.class);
        hmlBaseReviewActivity.tvSourceOfIncome = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_source_of_income, "field 'tvSourceOfIncome'", TextView.class);
        hmlBaseReviewActivity.tvCompanyName = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_company_name, "field 'tvCompanyName'", TextView.class);
        hmlBaseReviewActivity.tvWorkAddress = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_work_address, "field 'tvWorkAddress'", TextView.class);
        hmlBaseReviewActivity.tvWorkContactNumber = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_work_contact_number, "field 'tvWorkContactNumber'", TextView.class);
        hmlBaseReviewActivity.tvExperience = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_experience, "field 'tvExperience'", TextView.class);
        hmlBaseReviewActivity.grBusinessAccountGroup = (Group) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.gr_business_account, "field 'grBusinessAccountGroup'", Group.class);
        hmlBaseReviewActivity.tvBusinessAccountName = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_business_account_name, "field 'tvBusinessAccountName'", TextView.class);
        hmlBaseReviewActivity.tvBusinessAccountNumber = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_business_account_number, "field 'tvBusinessAccountNumber'", TextView.class);
        hmlBaseReviewActivity.cbTermsAndConditions = (CheckBox) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.cb_terms_and_conditions, "field 'cbTermsAndConditions'", CheckBox.class);
        hmlBaseReviewActivity.tvTermsAndConditions = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_terms_and_conditions, "field 'tvTermsAndConditions'", TextView.class);
        hmlBaseReviewActivity.tvConsentLabel = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_consent_label, "field 'tvConsentLabel'", TextView.class);
        hmlBaseReviewActivity.vwConsentBg = onStart.IconCompatParcelizer(view, R.id.vw_consent_bg, "field 'vwConsentBg'");
        hmlBaseReviewActivity.tvConsentDescription = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_consent_description, "field 'tvConsentDescription'", TextView.class);
        hmlBaseReviewActivity.spConsentSection = (Space) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.sp_consent_section_bottom, "field 'spConsentSection'", Space.class);
        hmlBaseReviewActivity.vwModelConsentSeparator = onStart.IconCompatParcelizer(view, R.id.vw_model_consent_separator, "field 'vwModelConsentSeparator'");
        hmlBaseReviewActivity.modelConsent = (CustomAcceptDeclineButtons) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.bts_model_consent, "field 'modelConsent'", CustomAcceptDeclineButtons.class);
        hmlBaseReviewActivity.vwCrossConsentSeparator = onStart.IconCompatParcelizer(view, R.id.vw_cross_consent_separator, "field 'vwCrossConsentSeparator'");
        hmlBaseReviewActivity.crossConsent = (CustomAcceptDeclineButtons) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.bts_cross_consent, "field 'crossConsent'", CustomAcceptDeclineButtons.class);
        hmlBaseReviewActivity.btConfirm = (Button) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.bt_confirm, "field 'btConfirm'", Button.class);
        hmlBaseReviewActivity.stampDutySeparator = onStart.IconCompatParcelizer(view, R.id.vw_separator_stamp_duty, "field 'stampDutySeparator'");
        hmlBaseReviewActivity.stampDutyLabel = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_stamp_duty_label, "field 'stampDutyLabel'", TextView.class);
        hmlBaseReviewActivity.stampDutyDescription = (TextView) onStart.MediaBrowserCompat$CustomActionResultReceiver(view, (int) R.id.tv_stamp_duty_description, "field 'stampDutyDescription'", TextView.class);
    }

    public final void read() {
        HmlBaseReviewActivity hmlBaseReviewActivity = this.MediaBrowserCompat$ItemReceiver;
        if (hmlBaseReviewActivity != null) {
            this.MediaBrowserCompat$ItemReceiver = null;
            hmlBaseReviewActivity.breadcrumbs = null;
            hmlBaseReviewActivity.separatorBreadcrumbs = null;
            hmlBaseReviewActivity.tvRequestedLoan = null;
            hmlBaseReviewActivity.tierPricingPromo = null;
            hmlBaseReviewActivity.promoSeparator = null;
            hmlBaseReviewActivity.tvRepaymentAmount = null;
            hmlBaseReviewActivity.tvDuration = null;
            hmlBaseReviewActivity.tvDurationDescription = null;
            hmlBaseReviewActivity.tvStartPaymentDate = null;
            hmlBaseReviewActivity.tvTitleLabel = null;
            hmlBaseReviewActivity.tvTitle = null;
            hmlBaseReviewActivity.tvNameLabel = null;
            hmlBaseReviewActivity.tvName = null;
            hmlBaseReviewActivity.tvEngNameLabel = null;
            hmlBaseReviewActivity.tvEngName = null;
            hmlBaseReviewActivity.tvBirthLabel = null;
            hmlBaseReviewActivity.tvBirth = null;
            hmlBaseReviewActivity.tvMarital = null;
            hmlBaseReviewActivity.tvEducation = null;
            hmlBaseReviewActivity.tvResidential = null;
            hmlBaseReviewActivity.tvNationalIdLabel = null;
            hmlBaseReviewActivity.tvNationalId = null;
            hmlBaseReviewActivity.tvLaserIdLabel = null;
            hmlBaseReviewActivity.tvLaserId = null;
            hmlBaseReviewActivity.tvIssueLabel = null;
            hmlBaseReviewActivity.tvIssue = null;
            hmlBaseReviewActivity.tvExpiry = null;
            hmlBaseReviewActivity.tvLaserLabel = null;
            hmlBaseReviewActivity.tvLaser = null;
            hmlBaseReviewActivity.tvMobileNumber = null;
            hmlBaseReviewActivity.tvEmail = null;
            hmlBaseReviewActivity.tvHomeAddressLabel = null;
            hmlBaseReviewActivity.tvHomeAddress = null;
            hmlBaseReviewActivity.tvMailingAddress = null;
            hmlBaseReviewActivity.tvMonthlyIncome = null;
            hmlBaseReviewActivity.ivPhotoAttached = null;
            hmlBaseReviewActivity.grRequiredDocuments = null;
            hmlBaseReviewActivity.tvPhotoAttached = null;
            hmlBaseReviewActivity.tvJob = null;
            hmlBaseReviewActivity.tvSourceOfIncome = null;
            hmlBaseReviewActivity.tvCompanyName = null;
            hmlBaseReviewActivity.tvWorkAddress = null;
            hmlBaseReviewActivity.tvWorkContactNumber = null;
            hmlBaseReviewActivity.tvExperience = null;
            hmlBaseReviewActivity.grBusinessAccountGroup = null;
            hmlBaseReviewActivity.tvBusinessAccountName = null;
            hmlBaseReviewActivity.tvBusinessAccountNumber = null;
            hmlBaseReviewActivity.cbTermsAndConditions = null;
            hmlBaseReviewActivity.tvTermsAndConditions = null;
            hmlBaseReviewActivity.tvConsentLabel = null;
            hmlBaseReviewActivity.vwConsentBg = null;
            hmlBaseReviewActivity.tvConsentDescription = null;
            hmlBaseReviewActivity.spConsentSection = null;
            hmlBaseReviewActivity.vwModelConsentSeparator = null;
            hmlBaseReviewActivity.modelConsent = null;
            hmlBaseReviewActivity.vwCrossConsentSeparator = null;
            hmlBaseReviewActivity.crossConsent = null;
            hmlBaseReviewActivity.btConfirm = null;
            hmlBaseReviewActivity.stampDutySeparator = null;
            hmlBaseReviewActivity.stampDutyLabel = null;
            hmlBaseReviewActivity.stampDutyDescription = null;
            super.read();
            return;
        }
        throw new IllegalStateException("Bindings already cleared.");
    }
}
