package p040o;

/* renamed from: o.AmountDetailsAdapter$DetailViewHolder */
public interface AmountDetailsAdapter$DetailViewHolder {
    DepositTransactionAdapter$ChildViewHolder_ViewBinding MediaBrowserCompat$CustomActionResultReceiver(DepositTransactionAdapter$ChildViewHolder_ViewBinding depositTransactionAdapter$ChildViewHolder_ViewBinding, PrepaidRequestMarketConductActivity prepaidRequestMarketConductActivity);

    DepositTransactionAdapter$ChildViewHolder_ViewBinding MediaBrowserCompat$ItemReceiver(DepositTransactionAdapter$ChildViewHolder_ViewBinding depositTransactionAdapter$ChildViewHolder_ViewBinding, ManageNotificationsActivity manageNotificationsActivity);
}
