package p040o;

import kotlin.NoWhenBranchMatchedException;
import p040o.FragmentBuilder_BindSmeLoanSelectorFragment;

/* renamed from: o.FragmentBuilder_BindStopChequeFragment$MediaBrowserCompat$ItemReceiver */
public final class C6813x1773b140<S> implements FragmentBuilder_BindJuristicResetPinLandingFragment<OnBoardingTutorialActivity> {
    public static final C6813x1773b140 MediaBrowserCompat$CustomActionResultReceiver = new C6813x1773b140();

    C6813x1773b140() {
    }

    public final /* synthetic */ Object read(Object obj, Object obj2) {
        Object obj3 = obj2;
        OnBoardingTutorialActivity onBoardingTutorialActivity = (OnBoardingTutorialActivity) obj;
        onGetStartedClick.write((Object) onBoardingTutorialActivity, "currentState");
        onGetStartedClick.write(obj3, "action");
        if (!(obj3 instanceof FragmentBuilder_BindSmeLoanSelectorFragment)) {
            obj3 = null;
        }
        FragmentBuilder_BindSmeLoanSelectorFragment fragmentBuilder_BindSmeLoanSelectorFragment = (FragmentBuilder_BindSmeLoanSelectorFragment) obj3;
        if (fragmentBuilder_BindSmeLoanSelectorFragment == null) {
            OnBoardingTutorialActivity onBoardingTutorialActivity2 = onBoardingTutorialActivity;
            return onBoardingTutorialActivity;
        } else if (fragmentBuilder_BindSmeLoanSelectorFragment instanceof FragmentBuilder_BindSmeLoanSelectorFragment.RatingCompat) {
            return OnBoardingTutorialActivity.read(onBoardingTutorialActivity, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, FragmentBuilder_BindStopChequeHistoryFragment.write(onBoardingTutorialActivity.PlaybackStateCompat$CustomAction, null.IconCompatParcelizer, Boolean.valueOf(null.IconCompatParcelizer), false, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (Throwable) null, false, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (Throwable) null, 252), (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 7864319);
        } else {
            OnBoardingTutorialActivity onBoardingTutorialActivity3 = onBoardingTutorialActivity;
            if (fragmentBuilder_BindSmeLoanSelectorFragment instanceof FragmentBuilder_BindSmeLoanSelectorFragment.read) {
                return OnBoardingTutorialActivity.read(onBoardingTutorialActivity3, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, FragmentBuilder_BindStopChequeHistoryFragment.write(onBoardingTutorialActivity3.PlaybackStateCompat$CustomAction, false, (Boolean) null, true, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (Throwable) null, false, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (Throwable) null, 227), (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 7864319);
            } else if (fragmentBuilder_BindSmeLoanSelectorFragment instanceof FragmentBuilder_BindSmeLoanSelectorFragment.MediaMetadataCompat) {
                return OnBoardingTutorialActivity.read(onBoardingTutorialActivity3, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, FragmentBuilder_BindStopChequeHistoryFragment.write(onBoardingTutorialActivity3.PlaybackStateCompat$CustomAction, false, (Boolean) null, false, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (Throwable) null, false, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (Throwable) null, 227), (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 7864319);
            } else if (fragmentBuilder_BindSmeLoanSelectorFragment instanceof FragmentBuilder_BindSmeLoanSelectorFragment.write) {
                FragmentBuilder_BindSmeLoanSelectorFragment.write write = (FragmentBuilder_BindSmeLoanSelectorFragment.write) fragmentBuilder_BindSmeLoanSelectorFragment;
                return OnBoardingTutorialActivity.read(onBoardingTutorialActivity3, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, FragmentBuilder_BindStopChequeHistoryFragment.write(onBoardingTutorialActivity3.PlaybackStateCompat$CustomAction, false, (Boolean) null, false, write.MediaBrowserCompat$CustomActionResultReceiver, write.write, false, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (Throwable) null, 227), (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 7864319);
            } else if (fragmentBuilder_BindSmeLoanSelectorFragment instanceof FragmentBuilder_BindSmeLoanSelectorFragment.IconCompatParcelizer) {
                return OnBoardingTutorialActivity.read(onBoardingTutorialActivity3, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, FragmentBuilder_BindStopChequeHistoryFragment.write(onBoardingTutorialActivity3.PlaybackStateCompat$CustomAction, false, (Boolean) null, false, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (Throwable) null, true, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (Throwable) null, 31), (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 7864319);
            } else if (fragmentBuilder_BindSmeLoanSelectorFragment instanceof C6803xe6fe6015) {
                return OnBoardingTutorialActivity.read(onBoardingTutorialActivity3, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, FragmentBuilder_BindStopChequeHistoryFragment.write(onBoardingTutorialActivity3.PlaybackStateCompat$CustomAction, ((C6803xe6fe6015) fragmentBuilder_BindSmeLoanSelectorFragment).MediaBrowserCompat$ItemReceiver, (Boolean) null, false, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (Throwable) null, false, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (Throwable) null, 30), (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 7864319);
            } else if (fragmentBuilder_BindSmeLoanSelectorFragment instanceof C6802xcc96eec6) {
                OnBoardingTutorialActivity onBoardingTutorialActivity4 = onBoardingTutorialActivity3;
                C6802xcc96eec6 fragmentBuilder_BindSmeLoanSelectorFragment$MediaBrowserCompat$CustomActionResultReceiver = (C6802xcc96eec6) fragmentBuilder_BindSmeLoanSelectorFragment;
                return OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, FragmentBuilder_BindStopChequeHistoryFragment.write(onBoardingTutorialActivity4.PlaybackStateCompat$CustomAction, false, (Boolean) null, false, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (Throwable) null, false, fragmentBuilder_BindSmeLoanSelectorFragment$MediaBrowserCompat$CustomActionResultReceiver.MediaBrowserCompat$CustomActionResultReceiver, fragmentBuilder_BindSmeLoanSelectorFragment$MediaBrowserCompat$CustomActionResultReceiver.IconCompatParcelizer, 31), (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 7864319);
            } else {
                throw new NoWhenBranchMatchedException();
            }
        }
    }
}
