package p040o;

/* renamed from: o.FragmentBuilder_BindSharingMomentsPreviewFragment */
public interface FragmentBuilder_BindSharingMomentsPreviewFragment {
    Object IconCompatParcelizer(String str, HmlNTBPromptPayNotFoundActivity<? super HmlVerifyPhoneValidateOtpActivity> hmlNTBPromptPayNotFoundActivity);

    Object MediaBrowserCompat$CustomActionResultReceiver(FragmentBuilder_BindHmlNtbOutcomeRejectFragment fragmentBuilder_BindHmlNtbOutcomeRejectFragment, FragmentBuilder_BindHmlOperatingBankFragment fragmentBuilder_BindHmlOperatingBankFragment, HmlNTBPromptPayNotFoundActivity<? super Boolean> hmlNTBPromptPayNotFoundActivity);

    Object MediaBrowserCompat$ItemReceiver(HmlNTBPromptPayNotFoundActivity<? super String> hmlNTBPromptPayNotFoundActivity);

    Object read(FragmentBuilder_BindHmlNtbOutcomeRejectFragment fragmentBuilder_BindHmlNtbOutcomeRejectFragment, FragmentBuilder_BindHmlOperatingBankFragment fragmentBuilder_BindHmlOperatingBankFragment, HmlNTBPromptPayNotFoundActivity<? super HmlVerifyPhoneValidateOtpActivity> hmlNTBPromptPayNotFoundActivity);
}
