package p040o;

import kotlin.NoWhenBranchMatchedException;
import p040o.FragmentBuilder_BindOccupationListFragment;
import p040o.FragmentBuilder_BindRemittanceInputFragment;

/* renamed from: o.FragmentBuilder_BindRemittanceLandingFragment */
public final class FragmentBuilder_BindRemittanceLandingFragment {
    public RepeaterParser MediaBrowserCompat$CustomActionResultReceiver = null;

    /* renamed from: o.FragmentBuilder_BindRemittanceLandingFragment$read */
    public static final class read<S> implements FragmentBuilder_BindJuristicResetPinLandingFragment<OnBoardingTutorialActivity> {
        public static final read IconCompatParcelizer = new read();

        read() {
        }

        public final /* synthetic */ Object read(Object obj, Object obj2) {
            OnBoardingTutorialActivity read;
            Object obj3 = obj2;
            OnBoardingTutorialActivity onBoardingTutorialActivity = (OnBoardingTutorialActivity) obj;
            onGetStartedClick.write((Object) onBoardingTutorialActivity, "currentState");
            onGetStartedClick.write(obj3, "action");
            FragmentBuilder_BindRemittanceInputFragment fragmentBuilder_BindRemittanceInputFragment = (FragmentBuilder_BindRemittanceInputFragment) (!(obj3 instanceof FragmentBuilder_BindRemittanceInputFragment) ? null : obj3);
            if (fragmentBuilder_BindRemittanceInputFragment != null) {
                if (fragmentBuilder_BindRemittanceInputFragment instanceof C6728x11d23707) {
                    read = OnBoardingTutorialActivity.read(onBoardingTutorialActivity, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, FragmentBuilder_BindRemittanceRecipientDetailFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity.read, false, (Long) null, false, false, 10), (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 7340031);
                } else {
                    OnBoardingTutorialActivity onBoardingTutorialActivity2 = onBoardingTutorialActivity;
                    if (onGetStartedClick.MediaBrowserCompat$ItemReceiver((Object) fragmentBuilder_BindRemittanceInputFragment, (Object) FragmentBuilder_BindRemittanceInputFragment.write.read)) {
                        OnBoardingTutorialActivity onBoardingTutorialActivity3 = onBoardingTutorialActivity2;
                        read = OnBoardingTutorialActivity.read(onBoardingTutorialActivity3, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, FragmentBuilder_BindRemittanceRecipientDetailFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity3.read, false, (Long) null, true, false, 11), (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 7340031);
                    } else {
                        OnBoardingTutorialActivity onBoardingTutorialActivity4 = onBoardingTutorialActivity2;
                        if (fragmentBuilder_BindRemittanceInputFragment instanceof FragmentBuilder_BindRemittanceInputFragment.MediaMetadataCompat) {
                            read = OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, FragmentBuilder_BindRemittanceRecipientDetailFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity4.read, true, (Long) null, false, false, 10), (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 7340031);
                        } else if (fragmentBuilder_BindRemittanceInputFragment instanceof FragmentBuilder_BindRemittanceInputFragment.MediaDescriptionCompat) {
                            read = OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, FragmentBuilder_BindRemittanceRecipientDetailFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity4.read, false, Long.valueOf(((FragmentBuilder_BindRemittanceInputFragment.MediaDescriptionCompat) fragmentBuilder_BindRemittanceInputFragment).MediaBrowserCompat$CustomActionResultReceiver), false, false, 13), (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 7340031);
                        } else if (onGetStartedClick.MediaBrowserCompat$ItemReceiver((Object) fragmentBuilder_BindRemittanceInputFragment, (Object) FragmentBuilder_BindRemittanceInputFragment.read.IconCompatParcelizer)) {
                            read = OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, FragmentBuilder_BindRemittanceRecipientDetailFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity4.read, false, (Long) null, false, true, 7), (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 7340031);
                        } else if (fragmentBuilder_BindRemittanceInputFragment instanceof FragmentBuilder_BindRemittanceInputFragment.IconCompatParcelizer) {
                            read = OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, FragmentBuilder_BindRemittanceRecipientDetailFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity4.read, ((FragmentBuilder_BindRemittanceInputFragment.IconCompatParcelizer) fragmentBuilder_BindRemittanceInputFragment).write, (Long) null, false, false, 6), (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 7340031);
                        } else if (fragmentBuilder_BindRemittanceInputFragment instanceof C6727x6666b638) {
                            read = OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, FragmentBuilder_BindRemittanceRecipientDetailFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity4.read, false, (Long) null, false, false, 6), (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 7340031);
                        } else {
                            throw new NoWhenBranchMatchedException();
                        }
                    }
                }
                return read;
            } else if (obj3 instanceof FragmentBuilder_BindOccupationListFragment.MediaMetadataCompat) {
                return OnBoardingTutorialActivity.read(onBoardingTutorialActivity, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, FragmentBuilder_BindRemittanceRecipientDetailFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity.read, false, (Long) null, false, true, 6), (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 7340031);
            } else {
                OnBoardingTutorialActivity onBoardingTutorialActivity5 = onBoardingTutorialActivity;
                return onBoardingTutorialActivity;
            }
        }
    }
}
