package p040o;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import kotlin.NoWhenBranchMatchedException;
import p040o.C6643x9654e915;
import p040o.FragmentBuilder_BindOccupationListFragment;

/* renamed from: o.FragmentBuilder_BindPrepaidRequestSuccessFragment */
public final class FragmentBuilder_BindPrepaidRequestSuccessFragment {
    public Map<String, List<getStartCap>> IconCompatParcelizer = new HashMap();
    public Map<String, setComposition> MediaBrowserCompat$ItemReceiver = new HashMap();
    public Map<String, resolveKeyPath> read = new HashMap();
    public setAnimationFromJson write = null;

    /* renamed from: o.FragmentBuilder_BindPrepaidRequestSuccessFragment$read */
    public static final class read<S> implements FragmentBuilder_BindJuristicResetPinLandingFragment<OnBoardingTutorialActivity> {
        public static final read read = new read();

        read() {
        }

        public final /* synthetic */ Object read(Object obj, Object obj2) {
            OnBoardingTutorialActivity read2;
            Object obj3 = obj2;
            OnBoardingTutorialActivity onBoardingTutorialActivity = (OnBoardingTutorialActivity) obj;
            onGetStartedClick.write((Object) onBoardingTutorialActivity, "currentState");
            onGetStartedClick.write(obj3, "action");
            C6643x9654e915 fragmentBuilder_BindPrepaidCashOutLandingAndInputToAccountFragment = (C6643x9654e915) (!(obj3 instanceof C6643x9654e915) ? null : obj3);
            if (fragmentBuilder_BindPrepaidCashOutLandingAndInputToAccountFragment != null) {
                if (fragmentBuilder_BindPrepaidCashOutLandingAndInputToAccountFragment instanceof C6643x9654e915.MediaMetadataCompat) {
                    read2 = OnBoardingTutorialActivity.read(onBoardingTutorialActivity, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, FragmentBuilder_BindPrepaidSuccessfulActivationFragment.IconCompatParcelizer(onBoardingTutorialActivity.MediaBrowserCompat$MediaItem, ((C6643x9654e915.MediaMetadataCompat) fragmentBuilder_BindPrepaidCashOutLandingAndInputToAccountFragment).read, false, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (Throwable) null, false, 30), (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8384511);
                } else {
                    OnBoardingTutorialActivity onBoardingTutorialActivity2 = onBoardingTutorialActivity;
                    if (onGetStartedClick.MediaBrowserCompat$ItemReceiver((Object) fragmentBuilder_BindPrepaidCashOutLandingAndInputToAccountFragment, (Object) C6643x9654e915.write.read)) {
                        OnBoardingTutorialActivity onBoardingTutorialActivity3 = onBoardingTutorialActivity2;
                        read2 = OnBoardingTutorialActivity.read(onBoardingTutorialActivity3, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, FragmentBuilder_BindPrepaidSuccessfulActivationFragment.IconCompatParcelizer(onBoardingTutorialActivity3.MediaBrowserCompat$MediaItem, (String) null, true, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (Throwable) null, false, 17), (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8384511);
                    } else {
                        OnBoardingTutorialActivity onBoardingTutorialActivity4 = onBoardingTutorialActivity2;
                        if (onGetStartedClick.MediaBrowserCompat$ItemReceiver((Object) fragmentBuilder_BindPrepaidCashOutLandingAndInputToAccountFragment, (Object) C6646x6e535f03.IconCompatParcelizer)) {
                            read2 = OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, FragmentBuilder_BindPrepaidSuccessfulActivationFragment.IconCompatParcelizer(onBoardingTutorialActivity4.MediaBrowserCompat$MediaItem, (String) null, false, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (Throwable) null, false, 17), (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8384511);
                        } else if (fragmentBuilder_BindPrepaidCashOutLandingAndInputToAccountFragment instanceof C6643x9654e915.MediaDescriptionCompat) {
                            C6643x9654e915.MediaDescriptionCompat mediaDescriptionCompat = (C6643x9654e915.MediaDescriptionCompat) fragmentBuilder_BindPrepaidCashOutLandingAndInputToAccountFragment;
                            read2 = OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, FragmentBuilder_BindPrepaidSuccessfulActivationFragment.IconCompatParcelizer(onBoardingTutorialActivity4.MediaBrowserCompat$MediaItem, (String) null, false, mediaDescriptionCompat.MediaBrowserCompat$CustomActionResultReceiver, mediaDescriptionCompat.read, false, 17), (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8384511);
                        } else if (onGetStartedClick.MediaBrowserCompat$ItemReceiver((Object) fragmentBuilder_BindPrepaidCashOutLandingAndInputToAccountFragment, (Object) C6645xf3940f31.write)) {
                            read2 = OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, FragmentBuilder_BindPrepaidSuccessfulActivationFragment.IconCompatParcelizer(onBoardingTutorialActivity4.MediaBrowserCompat$MediaItem, (String) null, false, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (Throwable) null, false, 30), (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8384511);
                        } else if (onGetStartedClick.MediaBrowserCompat$ItemReceiver((Object) fragmentBuilder_BindPrepaidCashOutLandingAndInputToAccountFragment, (Object) C6644x820dfce2.write)) {
                            read2 = OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, FragmentBuilder_BindPrepaidSuccessfulActivationFragment.IconCompatParcelizer(onBoardingTutorialActivity4.MediaBrowserCompat$MediaItem, (String) null, false, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (Throwable) null, true, 15), (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8384511);
                        } else if (fragmentBuilder_BindPrepaidCashOutLandingAndInputToAccountFragment instanceof C6643x9654e915.IconCompatParcelizer) {
                            read2 = OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, FragmentBuilder_BindPrepaidSuccessfulActivationFragment.IconCompatParcelizer(onBoardingTutorialActivity4.MediaBrowserCompat$MediaItem, ((C6643x9654e915.IconCompatParcelizer) fragmentBuilder_BindPrepaidCashOutLandingAndInputToAccountFragment).MediaBrowserCompat$CustomActionResultReceiver, false, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (Throwable) null, false, 14), (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8384511);
                        } else if (fragmentBuilder_BindPrepaidCashOutLandingAndInputToAccountFragment instanceof C6643x9654e915.read) {
                            read2 = OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, FragmentBuilder_BindPrepaidSuccessfulActivationFragment.IconCompatParcelizer(onBoardingTutorialActivity4.MediaBrowserCompat$MediaItem, (String) null, false, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (Throwable) null, false, 14), (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8384511);
                        } else {
                            throw new NoWhenBranchMatchedException();
                        }
                    }
                }
                return read2;
            } else if (obj3 instanceof FragmentBuilder_BindOccupationListFragment.MediaMetadataCompat) {
                return OnBoardingTutorialActivity.read(onBoardingTutorialActivity, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, FragmentBuilder_BindPrepaidSuccessfulActivationFragment.IconCompatParcelizer(onBoardingTutorialActivity.MediaBrowserCompat$MediaItem, (String) null, false, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (Throwable) null, false, 30), (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8384511);
            } else {
                OnBoardingTutorialActivity onBoardingTutorialActivity5 = onBoardingTutorialActivity;
                return onBoardingTutorialActivity;
            }
        }
    }
}
