package p040o;

import kotlin.NoWhenBranchMatchedException;
import p040o.EasycashCommercialInfoCaseModule;
import p040o.FragmentBuilder_BindMobileListFragment;
import p040o.FragmentBuilder_BindThirdPartyConsentFragment;

/* renamed from: o.FragmentBuilder_BindThirdPartySlipFragment */
public final class FragmentBuilder_BindThirdPartySlipFragment {

    /* renamed from: o.FragmentBuilder_BindThirdPartySlipFragment$IconCompatParcelizer */
    public static final class IconCompatParcelizer<S> implements FragmentBuilder_BindJuristicResetPinLandingFragment<OnBoardingTutorialActivity> {
        public static final IconCompatParcelizer MediaBrowserCompat$ItemReceiver = new IconCompatParcelizer();

        IconCompatParcelizer() {
        }

        public final /* synthetic */ Object read(Object obj, Object obj2) {
            OnBoardingTutorialActivity onBoardingTutorialActivity;
            FragmentBuilder_BindMwShopAddressDepartmentFragment fragmentBuilder_BindMwShopAddressDepartmentFragment;
            OnBoardingTutorialActivity onBoardingTutorialActivity2;
            String str;
            Object obj3 = obj2;
            OnBoardingTutorialActivity onBoardingTutorialActivity3 = (OnBoardingTutorialActivity) obj;
            onGetStartedClick.write((Object) onBoardingTutorialActivity3, "currentState");
            onGetStartedClick.write(obj3, "action");
            FragmentBuilder_BindThirdPartyConsentFragment fragmentBuilder_BindThirdPartyConsentFragment = (FragmentBuilder_BindThirdPartyConsentFragment) (!(obj3 instanceof FragmentBuilder_BindThirdPartyConsentFragment) ? null : obj3);
            if (fragmentBuilder_BindThirdPartyConsentFragment != null) {
                if (fragmentBuilder_BindThirdPartyConsentFragment instanceof C6831xda1855a8) {
                    FragmentBuilder_BindTodayTransactionsTabFragment fragmentBuilder_BindTodayTransactionsTabFragment = onBoardingTutorialActivity3.Keep;
                    C6831xda1855a8 fragmentBuilder_BindThirdPartyConsentFragment$MediaBrowserCompat$SearchResultReceiver = (C6831xda1855a8) fragmentBuilder_BindThirdPartyConsentFragment;
                    DeejungTransferLandingActivity deejungTransferLandingActivity = fragmentBuilder_BindThirdPartyConsentFragment$MediaBrowserCompat$SearchResultReceiver.read;
                    DeejungTransferLandingActivity deejungTransferLandingActivity2 = fragmentBuilder_BindThirdPartyConsentFragment$MediaBrowserCompat$SearchResultReceiver.read;
                    if (deejungTransferLandingActivity2 != null) {
                        str = deejungTransferLandingActivity2.ParcelableVolumeInfo;
                    } else {
                        str = null;
                    }
                    onBoardingTutorialActivity = onBoardingTutorialActivity3;
                    onBoardingTutorialActivity2 = OnBoardingTutorialActivity.read(onBoardingTutorialActivity3, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, FragmentBuilder_BindTodayTransactionsTabFragment.MediaBrowserCompat$CustomActionResultReceiver(fragmentBuilder_BindTodayTransactionsTabFragment, deejungTransferLandingActivity, (BaseAmortizationActivity) null, false, false, str, 14), (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8388095);
                } else {
                    onBoardingTutorialActivity = onBoardingTutorialActivity3;
                    if (fragmentBuilder_BindThirdPartyConsentFragment instanceof FragmentBuilder_BindThirdPartyConsentFragment.RatingCompat) {
                        OnBoardingTutorialActivity onBoardingTutorialActivity4 = onBoardingTutorialActivity;
                        onBoardingTutorialActivity2 = OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, FragmentBuilder_BindTodayTransactionsTabFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity4.Keep, (DeejungTransferLandingActivity) null, ((FragmentBuilder_BindThirdPartyConsentFragment.RatingCompat) fragmentBuilder_BindThirdPartyConsentFragment).write, false, false, (String) null, 29), (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8388095);
                    } else if (fragmentBuilder_BindThirdPartyConsentFragment instanceof FragmentBuilder_BindThirdPartyConsentFragment.read) {
                        OnBoardingTutorialActivity onBoardingTutorialActivity5 = onBoardingTutorialActivity;
                        onBoardingTutorialActivity2 = OnBoardingTutorialActivity.read(onBoardingTutorialActivity5, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, FragmentBuilder_BindTodayTransactionsTabFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity5.Keep, (DeejungTransferLandingActivity) null, (BaseAmortizationActivity) null, ((FragmentBuilder_BindThirdPartyConsentFragment.read) fragmentBuilder_BindThirdPartyConsentFragment).MediaBrowserCompat$CustomActionResultReceiver, false, (String) null, 27), (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8388095);
                    } else if (onGetStartedClick.MediaBrowserCompat$ItemReceiver((Object) fragmentBuilder_BindThirdPartyConsentFragment, (Object) C6830xb8d87ad6.IconCompatParcelizer)) {
                        OnBoardingTutorialActivity onBoardingTutorialActivity6 = onBoardingTutorialActivity;
                        onBoardingTutorialActivity2 = OnBoardingTutorialActivity.read(onBoardingTutorialActivity6, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, FragmentBuilder_BindTodayTransactionsTabFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity6.Keep, (DeejungTransferLandingActivity) null, BaseAmortizationActivity.ELEMENT_TAB, false, false, (String) null, 21), (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8388095);
                    } else if (onGetStartedClick.MediaBrowserCompat$ItemReceiver((Object) fragmentBuilder_BindThirdPartyConsentFragment, (Object) C6829x6026a3c7.IconCompatParcelizer)) {
                        OnBoardingTutorialActivity onBoardingTutorialActivity7 = onBoardingTutorialActivity;
                        onBoardingTutorialActivity2 = OnBoardingTutorialActivity.read(onBoardingTutorialActivity7, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, FragmentBuilder_BindTodayTransactionsTabFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity7.Keep, (DeejungTransferLandingActivity) null, (BaseAmortizationActivity) null, false, true, (String) null, 23), (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8388095);
                    } else if (onGetStartedClick.MediaBrowserCompat$ItemReceiver((Object) fragmentBuilder_BindThirdPartyConsentFragment, (Object) FragmentBuilder_BindThirdPartyConsentFragment.write.MediaBrowserCompat$ItemReceiver) || onGetStartedClick.MediaBrowserCompat$ItemReceiver((Object) fragmentBuilder_BindThirdPartyConsentFragment, (Object) FragmentBuilder_BindThirdPartyConsentFragment.IconCompatParcelizer.read)) {
                        onBoardingTutorialActivity2 = onBoardingTutorialActivity;
                    } else {
                        throw new NoWhenBranchMatchedException();
                    }
                }
                if (onBoardingTutorialActivity2 != null) {
                    return onBoardingTutorialActivity2;
                }
            } else {
                onBoardingTutorialActivity = onBoardingTutorialActivity3;
            }
            if (obj3 instanceof FragmentBuilder_BindMobileListFragment.RatingCompat) {
                FragmentBuilder_BindMileageAirlineFieldDetailsFragment fragmentBuilder_BindMileageAirlineFieldDetailsFragment = ((FragmentBuilder_BindMobileListFragment.RatingCompat) obj3).MediaBrowserCompat$CustomActionResultReceiver;
                if (fragmentBuilder_BindMileageAirlineFieldDetailsFragment != null) {
                    fragmentBuilder_BindMwShopAddressDepartmentFragment = fragmentBuilder_BindMileageAirlineFieldDetailsFragment.MediaBrowserCompat$CustomActionResultReceiver;
                } else {
                    fragmentBuilder_BindMwShopAddressDepartmentFragment = null;
                }
                if (fragmentBuilder_BindMwShopAddressDepartmentFragment != FragmentBuilder_BindMwShopAddressDepartmentFragment.DESTROYED) {
                    return onBoardingTutorialActivity;
                }
                OnBoardingTutorialActivity onBoardingTutorialActivity8 = onBoardingTutorialActivity;
                return OnBoardingTutorialActivity.read(onBoardingTutorialActivity8, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, FragmentBuilder_BindTodayTransactionsTabFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity8.Keep, (DeejungTransferLandingActivity) null, (BaseAmortizationActivity) null, false, false, (String) null, 30), (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8388095);
            }
            OnBoardingTutorialActivity onBoardingTutorialActivity9 = onBoardingTutorialActivity;
            if (obj3 instanceof EasycashCommercialInfoCaseModule.read) {
                return OnBoardingTutorialActivity.read(onBoardingTutorialActivity9, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, FragmentBuilder_BindTodayTransactionsTabFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity9.Keep, (DeejungTransferLandingActivity) null, (BaseAmortizationActivity) null, false, false, (String) null, 30), (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8388095);
            }
            OnBoardingTutorialActivity onBoardingTutorialActivity10 = onBoardingTutorialActivity9;
            if (obj3 instanceof C6865x419be8c4) {
                C6865x419be8c4 fragmentBuilder_BindTransferToPromptPayStep1Fragment$MediaBrowserCompat$ItemReceiver = (C6865x419be8c4) obj3;
                if (fragmentBuilder_BindTransferToPromptPayStep1Fragment$MediaBrowserCompat$ItemReceiver.MediaBrowserCompat$CustomActionResultReceiver == FragmentBuilder_BindVerifyIdentityFragment.DESIGN_TIME_OFF || fragmentBuilder_BindTransferToPromptPayStep1Fragment$MediaBrowserCompat$ItemReceiver.MediaBrowserCompat$CustomActionResultReceiver == FragmentBuilder_BindVerifyIdentityFragment.RUNTIME) {
                    FragmentBuilder_BindTodayTransactionsTabFragment fragmentBuilder_BindTodayTransactionsTabFragment2 = r0;
                    FragmentBuilder_BindTodayTransactionsTabFragment fragmentBuilder_BindTodayTransactionsTabFragment3 = new FragmentBuilder_BindTodayTransactionsTabFragment((byte) 0);
                    return OnBoardingTutorialActivity.read(onBoardingTutorialActivity10, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, fragmentBuilder_BindTodayTransactionsTabFragment2, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8388095);
                }
            } else if (obj3 instanceof C6608x9567a686) {
                FragmentBuilder_BindTodayTransactionsTabFragment fragmentBuilder_BindTodayTransactionsTabFragment4 = r0;
                FragmentBuilder_BindTodayTransactionsTabFragment fragmentBuilder_BindTodayTransactionsTabFragment5 = new FragmentBuilder_BindTodayTransactionsTabFragment((byte) 0);
                return OnBoardingTutorialActivity.read(onBoardingTutorialActivity10, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, fragmentBuilder_BindTodayTransactionsTabFragment4, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8388095);
            } else if (obj3 instanceof C6681x7533d6fb) {
                FragmentBuilder_BindTodayTransactionsTabFragment fragmentBuilder_BindTodayTransactionsTabFragment6 = r0;
                FragmentBuilder_BindTodayTransactionsTabFragment fragmentBuilder_BindTodayTransactionsTabFragment7 = new FragmentBuilder_BindTodayTransactionsTabFragment((byte) 0);
                return OnBoardingTutorialActivity.read(onBoardingTutorialActivity10, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, fragmentBuilder_BindTodayTransactionsTabFragment6, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8388095);
            } else if (obj3 instanceof C6845xc069f6e7) {
                FragmentBuilder_BindTodayTransactionsTabFragment fragmentBuilder_BindTodayTransactionsTabFragment8 = r0;
                FragmentBuilder_BindTodayTransactionsTabFragment fragmentBuilder_BindTodayTransactionsTabFragment9 = new FragmentBuilder_BindTodayTransactionsTabFragment((byte) 0);
                return OnBoardingTutorialActivity.read(onBoardingTutorialActivity10, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, fragmentBuilder_BindTodayTransactionsTabFragment8, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8388095);
            }
            return onBoardingTutorialActivity10;
        }
    }
}
