package p040o;

import java.util.List;
import kotlin.NoWhenBranchMatchedException;
import p040o.FragmentBuilder_BindOccupationListFragment;
import p040o.FragmentBuilder_BindSensitiveCSentFragment;

@HmlSetNTBPinActivity
/* renamed from: o.FragmentBuilder_BindSentFragment */
public final class FragmentBuilder_BindSentFragment {
    public List<? extends inject_base64Decoder> MediaBrowserCompat$CustomActionResultReceiver;

    /* renamed from: o.FragmentBuilder_BindSentFragment$IconCompatParcelizer */
    public static final class IconCompatParcelizer<S> implements FragmentBuilder_BindJuristicResetPinLandingFragment<OnBoardingTutorialActivity> {
        public static final IconCompatParcelizer write = new IconCompatParcelizer();

        IconCompatParcelizer() {
        }

        public final /* synthetic */ Object read(Object obj, Object obj2) {
            OnBoardingTutorialActivity onBoardingTutorialActivity;
            OnBoardingTutorialActivity onBoardingTutorialActivity2;
            Object obj3 = obj2;
            OnBoardingTutorialActivity onBoardingTutorialActivity3 = (OnBoardingTutorialActivity) obj;
            onGetStartedClick.write((Object) onBoardingTutorialActivity3, "currentState");
            onGetStartedClick.write(obj3, "action");
            FragmentBuilder_BindSensitiveCSentFragment fragmentBuilder_BindSensitiveCSentFragment = (FragmentBuilder_BindSensitiveCSentFragment) (!(obj3 instanceof FragmentBuilder_BindSensitiveCSentFragment) ? null : obj3);
            if (fragmentBuilder_BindSensitiveCSentFragment != null) {
                if (fragmentBuilder_BindSensitiveCSentFragment instanceof C1193x41a50793) {
                    C1193x41a50793 fragmentBuilder_BindSensitiveCSentFragment$MediaBrowserCompat$CustomActionResultReceiver = (C1193x41a50793) fragmentBuilder_BindSensitiveCSentFragment;
                    Integer num = fragmentBuilder_BindSensitiveCSentFragment$MediaBrowserCompat$CustomActionResultReceiver.read.write;
                    if (num == null) {
                        num = onBoardingTutorialActivity3.MediaSessionCompat$ResultReceiverWrapper.MediaBrowserCompat$CustomActionResultReceiver.write;
                    }
                    onBoardingTutorialActivity = onBoardingTutorialActivity3;
                    onBoardingTutorialActivity2 = OnBoardingTutorialActivity.read(onBoardingTutorialActivity3, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, FragmentBuilder_BindSetDetailFragment.read(onBoardingTutorialActivity3.MediaSessionCompat$ResultReceiverWrapper, new FragmentBuilder_BindSelectPurposeFragment(fragmentBuilder_BindSensitiveCSentFragment$MediaBrowserCompat$CustomActionResultReceiver.read.IconCompatParcelizer, num), (Boolean) null, (String) null, false, false, 30), (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8388575);
                } else {
                    onBoardingTutorialActivity = onBoardingTutorialActivity3;
                    if (fragmentBuilder_BindSensitiveCSentFragment instanceof FragmentBuilder_BindSensitiveCSentFragment.MediaDescriptionCompat) {
                        OnBoardingTutorialActivity onBoardingTutorialActivity4 = onBoardingTutorialActivity;
                        onBoardingTutorialActivity2 = OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, FragmentBuilder_BindSetDetailFragment.read(onBoardingTutorialActivity4.MediaSessionCompat$ResultReceiverWrapper, (FragmentBuilder_BindSelectPurposeFragment) null, Boolean.valueOf(((FragmentBuilder_BindSensitiveCSentFragment.MediaDescriptionCompat) fragmentBuilder_BindSensitiveCSentFragment).write), (String) null, false, false, 29), (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8388575);
                    } else {
                        if (!(fragmentBuilder_BindSensitiveCSentFragment instanceof FragmentBuilder_BindSensitiveCSentFragment.MediaMetadataCompat) && !onGetStartedClick.MediaBrowserCompat$ItemReceiver((Object) fragmentBuilder_BindSensitiveCSentFragment, (Object) C6778xc3f08274.IconCompatParcelizer)) {
                            if (fragmentBuilder_BindSensitiveCSentFragment instanceof FragmentBuilder_BindSensitiveCSentFragment.RatingCompat) {
                                OnBoardingTutorialActivity onBoardingTutorialActivity5 = onBoardingTutorialActivity;
                                onBoardingTutorialActivity2 = OnBoardingTutorialActivity.read(onBoardingTutorialActivity5, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, FragmentBuilder_BindSetDetailFragment.read(onBoardingTutorialActivity5.MediaSessionCompat$ResultReceiverWrapper, (FragmentBuilder_BindSelectPurposeFragment) null, (Boolean) null, ((FragmentBuilder_BindSensitiveCSentFragment.RatingCompat) fragmentBuilder_BindSensitiveCSentFragment).read, false, false, 11), (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8388575);
                            } else if (!onGetStartedClick.MediaBrowserCompat$ItemReceiver((Object) fragmentBuilder_BindSensitiveCSentFragment, (Object) C6777xedfb8f97.MediaBrowserCompat$ItemReceiver) && !(fragmentBuilder_BindSensitiveCSentFragment instanceof FragmentBuilder_BindSensitiveCSentFragment.read)) {
                                if (fragmentBuilder_BindSensitiveCSentFragment instanceof FragmentBuilder_BindSensitiveCSentFragment.write) {
                                    OnBoardingTutorialActivity onBoardingTutorialActivity6 = onBoardingTutorialActivity;
                                    onBoardingTutorialActivity2 = OnBoardingTutorialActivity.read(onBoardingTutorialActivity6, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, FragmentBuilder_BindSetDetailFragment.read(onBoardingTutorialActivity6.MediaSessionCompat$ResultReceiverWrapper, (FragmentBuilder_BindSelectPurposeFragment) null, (Boolean) null, (String) null, true, false, 7), (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8388575);
                                } else if (fragmentBuilder_BindSensitiveCSentFragment instanceof FragmentBuilder_BindSensitiveCSentFragment.IconCompatParcelizer) {
                                    OnBoardingTutorialActivity onBoardingTutorialActivity7 = onBoardingTutorialActivity;
                                    onBoardingTutorialActivity2 = OnBoardingTutorialActivity.read(onBoardingTutorialActivity7, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, FragmentBuilder_BindSetDetailFragment.read(onBoardingTutorialActivity7.MediaSessionCompat$ResultReceiverWrapper, (FragmentBuilder_BindSelectPurposeFragment) null, (Boolean) null, (String) null, false, true, 7), (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8388575);
                                } else if (fragmentBuilder_BindSensitiveCSentFragment instanceof C6776xc36033a2) {
                                    OnBoardingTutorialActivity onBoardingTutorialActivity8 = onBoardingTutorialActivity;
                                    onBoardingTutorialActivity2 = OnBoardingTutorialActivity.read(onBoardingTutorialActivity8, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, FragmentBuilder_BindSetDetailFragment.read(onBoardingTutorialActivity8.MediaSessionCompat$ResultReceiverWrapper, (FragmentBuilder_BindSelectPurposeFragment) null, (Boolean) null, (String) null, false, false, 7), (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8388575);
                                } else {
                                    throw new NoWhenBranchMatchedException();
                                }
                            }
                        }
                        onBoardingTutorialActivity2 = onBoardingTutorialActivity;
                    }
                }
                if (onBoardingTutorialActivity2 != null) {
                    return onBoardingTutorialActivity2;
                }
            } else {
                onBoardingTutorialActivity = onBoardingTutorialActivity3;
            }
            if (!(obj3 instanceof FragmentBuilder_BindOccupationListFragment.MediaMetadataCompat)) {
                return onBoardingTutorialActivity;
            }
            OnBoardingTutorialActivity onBoardingTutorialActivity9 = onBoardingTutorialActivity;
            return OnBoardingTutorialActivity.read(onBoardingTutorialActivity9, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, FragmentBuilder_BindSetDetailFragment.read(onBoardingTutorialActivity9.MediaSessionCompat$ResultReceiverWrapper, (FragmentBuilder_BindSelectPurposeFragment) null, (Boolean) null, (String) null, false, false, 15), (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, (FragmentBuilder_BindRegalQuestionnaireFragment) null, 8388575);
        }
    }
}
