package p040o;

/* renamed from: o.FragmentBuilder_BindDialogDialogQuickBalanceFragment */
public enum FragmentBuilder_BindDialogDialogQuickBalanceFragment {
    ADS_ID_KEY("ADS_ID_KEY"),
    CREDIT_CARD_ALL_COACH_MARK_DONE_KEY("CREDIT_CARD_ALL_COACH_MARK_DONE_KEY"),
    KEY_SEEN_CARDLESS_COACHMARK("cardless_coachmark"),
    KEY_SEEN_DEBIT_CARD_COACH_MARKS("KEY_DEBIT_CARD_COACH_MARKS"),
    KEY_SEEN_MERCHANT_WALLET_COACH_MARKS("KEY_SEEN_MERCHANT_WALLET_COACH_MARKS"),
    KEY_SEEN_MYQR_COACH_MARKS("KEY_MYQR_COACH_MARKS"),
    KEY_SEEN_QR_PAYMENT_COACH_MARKS("KEY_QR_PAYMENT_COACH_MARKS"),
    KEY_SEEN_REMITTANCE_COACH_MARKS("KEY_SEEN_REMITTANCE_COACH_MARKS"),
    KEY_SEEN_SERVICE_AT_BANKING_COACH_MARKS("KEY_SERVICE_AT_BANKING_COACH_MARKS"),
    KEY_TRAVELCARD_COACH_MARKS("KEY_TRAVELCARD_COACH_MARKS"),
    LIFE_STYLE_TUTORIAL_ALL_DONE_KEY("LIFE_STYLE_TUTORIAL_ALL_DONE_KEY"),
    SUMMARY_ADS_ID_KEY("SUMMARY_ADS_ID_KEY");
    
    public final String value;

    private FragmentBuilder_BindDialogDialogQuickBalanceFragment(String str) {
        this.value = str;
    }
}
