package p040o;

import java.util.List;
import kotlin.NoWhenBranchMatchedException;
import p040o.FragmentBuilder_BindOccupationListFragment;
import p040o.FragmentBuilder_BindPurchasedTabFragment;
import p040o.zzby;
import p040o.zzca;
import p040o.zzct;
import p040o.zzcz;
import p040o.zziu;
import p040o.zzjx;

@HmlSetNTBPinActivity
/* renamed from: o.FragmentBuilder_BindQuickTopUpFragment */
public final class FragmentBuilder_BindQuickTopUpFragment {
    public String AlertController$RecycleListView;
    public List<PlacePhotoMetadataResult> AppCompatActivity;
    public String AppCompatDelegateImpl$ListMenuDecorView;
    public String AppCompatDialogFragment;
    public setContentDescription IconCompatParcelizer;
    public zzjx.zza.C10770zza Keep;
    public zzca.zzf.zza MediaBrowserCompat$CustomActionResultReceiver;
    public zzcz.zzh.zza MediaBrowserCompat$ItemReceiver;
    public String MediaBrowserCompat$MediaItem;
    public zzcz.zza.C10765zza MediaBrowserCompat$SearchResultReceiver;

    /* renamed from: MediaControllerCompat$MediaControllerImplApi21$ExtraBinderRequestResultReceiver */
    public removeActivityTransitionUpdates f3151x50fd9e4a;
    public zzby.zza.read MediaDescriptionCompat = zzby.zza.read.NO_REUPLOADED;
    public String MediaMetadataCompat;
    public String MediaSessionCompat$QueueItem;
    public zzjx.zze MediaSessionCompat$ResultReceiverWrapper;
    public setContentDescription MediaSessionCompat$Token;
    public String ParcelableVolumeInfo;
    public Boolean PlaybackStateCompat;
    public setContentDescription PlaybackStateCompat$CustomAction;
    public zzct.zza RatingCompat = zzct.zza.CONSUMER;
    public zzcz.zzg read;
    public zziu.zzc setBackgroundResource;
    public setContentDescription setChecked;
    public StreetViewPanoramaFragment setContentView;
    public zzwd setExpandedFormat;
    public String setHasDecor;
    public String write;

    /* renamed from: o.FragmentBuilder_BindQuickTopUpFragment$IconCompatParcelizer */
    public static final class IconCompatParcelizer<S> implements FragmentBuilder_BindJuristicResetPinLandingFragment<OnBoardingTutorialActivity> {
        public static final IconCompatParcelizer MediaBrowserCompat$CustomActionResultReceiver = new IconCompatParcelizer();

        IconCompatParcelizer() {
        }

        public final /* synthetic */ Object read(Object obj, Object obj2) {
            OnBoardingTutorialActivity read;
            List<FragmentBuilder_BindHmlOutcomeRejectFragment> list;
            Object obj3 = obj2;
            OnBoardingTutorialActivity onBoardingTutorialActivity = (OnBoardingTutorialActivity) obj;
            onGetStartedClick.write((Object) onBoardingTutorialActivity, "currentState");
            onGetStartedClick.write(obj3, "action");
            FragmentBuilder_BindRegistrationLandingFragment fragmentBuilder_BindRegistrationLandingFragment = null;
            FragmentBuilder_BindPurchasedTabFragment fragmentBuilder_BindPurchasedTabFragment = (FragmentBuilder_BindPurchasedTabFragment) (!(obj3 instanceof FragmentBuilder_BindPurchasedTabFragment) ? null : obj3);
            if (fragmentBuilder_BindPurchasedTabFragment != null) {
                if (onGetStartedClick.MediaBrowserCompat$ItemReceiver((Object) fragmentBuilder_BindPurchasedTabFragment, (Object) C6691xb2a61b80.MediaBrowserCompat$ItemReceiver)) {
                    read = OnBoardingTutorialActivity.read(onBoardingTutorialActivity, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, FragmentBuilder_BindRegalQuestionnaireFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity.MediaBrowserCompat$ItemReceiver, true, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (List) null, (FragmentBuilder_BindRegistrationLandingFragment) null, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, false, 4088), 4194303);
                } else {
                    OnBoardingTutorialActivity onBoardingTutorialActivity2 = onBoardingTutorialActivity;
                    if (fragmentBuilder_BindPurchasedTabFragment instanceof FragmentBuilder_BindPurchasedTabFragment.write) {
                        OnBoardingTutorialActivity onBoardingTutorialActivity3 = onBoardingTutorialActivity2;
                        FragmentBuilder_BindPurchasedTabFragment.write write = (FragmentBuilder_BindPurchasedTabFragment.write) fragmentBuilder_BindPurchasedTabFragment;
                        read = OnBoardingTutorialActivity.read(onBoardingTutorialActivity3, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, FragmentBuilder_BindRegalQuestionnaireFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity3.MediaBrowserCompat$ItemReceiver, false, write.write, write.MediaBrowserCompat$CustomActionResultReceiver, (List) null, (FragmentBuilder_BindRegistrationLandingFragment) null, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, false, 4088), 4194303);
                    } else {
                        OnBoardingTutorialActivity onBoardingTutorialActivity4 = onBoardingTutorialActivity2;
                        if (fragmentBuilder_BindPurchasedTabFragment instanceof FragmentBuilder_BindPurchasedTabFragment.read) {
                            FragmentBuilder_BindRegalQuestionnaireFragment fragmentBuilder_BindRegalQuestionnaireFragment = onBoardingTutorialActivity4.MediaBrowserCompat$ItemReceiver;
                            FragmentBuilder_BindPurchasedTabFragment.read read2 = (FragmentBuilder_BindPurchasedTabFragment.read) fragmentBuilder_BindPurchasedTabFragment;
                            FragmentBuilder_BindPurchaseProfileManagementFragment fragmentBuilder_BindPurchaseProfileManagementFragment = read2.IconCompatParcelizer;
                            List<FragmentBuilder_BindHmlOutcomeRejectFragment> list2 = fragmentBuilder_BindPurchaseProfileManagementFragment != null ? fragmentBuilder_BindPurchaseProfileManagementFragment.read : null;
                            FragmentBuilder_BindPurchaseProfileManagementFragment fragmentBuilder_BindPurchaseProfileManagementFragment2 = read2.IconCompatParcelizer;
                            if (fragmentBuilder_BindPurchaseProfileManagementFragment2 != null) {
                                fragmentBuilder_BindRegistrationLandingFragment = fragmentBuilder_BindPurchaseProfileManagementFragment2.MediaBrowserCompat$ItemReceiver;
                            }
                            read = OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, FragmentBuilder_BindRegalQuestionnaireFragment.MediaBrowserCompat$CustomActionResultReceiver(fragmentBuilder_BindRegalQuestionnaireFragment, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, list2, fragmentBuilder_BindRegistrationLandingFragment, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, false, 4070), 4194303);
                        } else if (onGetStartedClick.MediaBrowserCompat$ItemReceiver((Object) fragmentBuilder_BindPurchasedTabFragment, (Object) C6693x1873100a.write)) {
                            read = OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, FragmentBuilder_BindRegalQuestionnaireFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity4.MediaBrowserCompat$ItemReceiver, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (List) null, (FragmentBuilder_BindRegistrationLandingFragment) null, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, false, 4094), 4194303);
                        } else if (onGetStartedClick.MediaBrowserCompat$ItemReceiver((Object) fragmentBuilder_BindPurchasedTabFragment, (Object) FragmentBuilder_BindPurchasedTabFragment.IconCompatParcelizer.read)) {
                            read = OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, FragmentBuilder_BindRegalQuestionnaireFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity4.MediaBrowserCompat$ItemReceiver, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (List) null, (FragmentBuilder_BindRegistrationLandingFragment) null, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, false, 4094), 4194303);
                        } else if (onGetStartedClick.MediaBrowserCompat$ItemReceiver((Object) fragmentBuilder_BindPurchasedTabFragment, (Object) C6692xabecfa4f.MediaBrowserCompat$ItemReceiver)) {
                            read = OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, FragmentBuilder_BindRegalQuestionnaireFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity4.MediaBrowserCompat$ItemReceiver, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (List) null, (FragmentBuilder_BindRegistrationLandingFragment) null, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, false, 4094), 4194303);
                        } else if (onGetStartedClick.MediaBrowserCompat$ItemReceiver((Object) fragmentBuilder_BindPurchasedTabFragment, (Object) FragmentBuilder_BindPurchasedTabFragment.RatingCompat.MediaBrowserCompat$CustomActionResultReceiver)) {
                            read = OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, FragmentBuilder_BindRegalQuestionnaireFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity4.MediaBrowserCompat$ItemReceiver, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (List) null, (FragmentBuilder_BindRegistrationLandingFragment) null, true, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, false, 3871), 4194303);
                        } else if (fragmentBuilder_BindPurchasedTabFragment instanceof C6694x80964c21) {
                            C6694x80964c21 fragmentBuilder_BindPurchasedTabFragment$MediaBrowserCompat$SearchResultReceiver = (C6694x80964c21) fragmentBuilder_BindPurchasedTabFragment;
                            read = OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, FragmentBuilder_BindRegalQuestionnaireFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity4.MediaBrowserCompat$ItemReceiver, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (List) null, (FragmentBuilder_BindRegistrationLandingFragment) null, false, fragmentBuilder_BindPurchasedTabFragment$MediaBrowserCompat$SearchResultReceiver.MediaBrowserCompat$CustomActionResultReceiver, fragmentBuilder_BindPurchasedTabFragment$MediaBrowserCompat$SearchResultReceiver.IconCompatParcelizer, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, false, 3847), 4194303);
                        } else if (fragmentBuilder_BindPurchasedTabFragment instanceof FragmentBuilder_BindPurchasedTabFragment.MediaDescriptionCompat) {
                            FragmentBuilder_BindRegalQuestionnaireFragment fragmentBuilder_BindRegalQuestionnaireFragment2 = onBoardingTutorialActivity4.MediaBrowserCompat$ItemReceiver;
                            FragmentBuilder_BindPurchasedTabFragment.MediaDescriptionCompat mediaDescriptionCompat = (FragmentBuilder_BindPurchasedTabFragment.MediaDescriptionCompat) fragmentBuilder_BindPurchasedTabFragment;
                            FragmentBuilder_BindPurchaseProfileManagementFragment fragmentBuilder_BindPurchaseProfileManagementFragment3 = mediaDescriptionCompat.read;
                            if (fragmentBuilder_BindPurchaseProfileManagementFragment3 != null) {
                                list = fragmentBuilder_BindPurchaseProfileManagementFragment3.read;
                            } else {
                                list = null;
                            }
                            FragmentBuilder_BindPurchaseProfileManagementFragment fragmentBuilder_BindPurchaseProfileManagementFragment4 = mediaDescriptionCompat.read;
                            if (fragmentBuilder_BindPurchaseProfileManagementFragment4 != null) {
                                fragmentBuilder_BindRegistrationLandingFragment = fragmentBuilder_BindPurchaseProfileManagementFragment4.MediaBrowserCompat$ItemReceiver;
                            }
                            read = OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, FragmentBuilder_BindRegalQuestionnaireFragment.MediaBrowserCompat$CustomActionResultReceiver(fragmentBuilder_BindRegalQuestionnaireFragment2, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, list, fragmentBuilder_BindRegistrationLandingFragment, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, true, 1991), 4194303);
                        } else if (onGetStartedClick.MediaBrowserCompat$ItemReceiver((Object) fragmentBuilder_BindPurchasedTabFragment, (Object) FragmentBuilder_BindPurchasedTabFragment.MediaMetadataCompat.MediaBrowserCompat$CustomActionResultReceiver)) {
                            read = OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, FragmentBuilder_BindRegalQuestionnaireFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity4.MediaBrowserCompat$ItemReceiver, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (List) null, (FragmentBuilder_BindRegistrationLandingFragment) null, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, true, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, false, 2303), 4194303);
                        } else if (onGetStartedClick.MediaBrowserCompat$ItemReceiver((Object) fragmentBuilder_BindPurchasedTabFragment, (Object) C6696x7bf57ea8.read)) {
                            read = OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, FragmentBuilder_BindRegalQuestionnaireFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity4.MediaBrowserCompat$ItemReceiver, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (List) null, (FragmentBuilder_BindRegistrationLandingFragment) null, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, false, 3839), 4194303);
                        } else if (fragmentBuilder_BindPurchasedTabFragment instanceof C6695x199ddfd9) {
                            C6695x199ddfd9 fragmentBuilder_BindPurchasedTabFragment$MediaControllerCompat$MediaControllerImplApi21$ExtraBinderRequestResultReceiver = (C6695x199ddfd9) fragmentBuilder_BindPurchasedTabFragment;
                            read = OnBoardingTutorialActivity.read(onBoardingTutorialActivity4, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, FragmentBuilder_BindRegalQuestionnaireFragment.MediaBrowserCompat$CustomActionResultReceiver(onBoardingTutorialActivity4.MediaBrowserCompat$ItemReceiver, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, (List) null, (FragmentBuilder_BindRegistrationLandingFragment) null, false, (Throwable) null, (FragmentBuilder_BindMerchantWalletSelectorFragment) null, false, fragmentBuilder_BindPurchasedTabFragment$MediaControllerCompat$MediaControllerImplApi21$ExtraBinderRequestResultReceiver.IconCompatParcelizer, fragmentBuilder_BindPurchasedTabFragment$MediaControllerCompat$MediaControllerImplApi21$ExtraBinderRequestResultReceiver.MediaBrowserCompat$CustomActionResultReceiver, false, 2303), 4194303);
                        } else {
                            throw new NoWhenBranchMatchedException();
                        }
                    }
                }
                return read;
            }
            OnBoardingTutorialActivity onBoardingTutorialActivity5 = onBoardingTutorialActivity;
            if (!(obj3 instanceof FragmentBuilder_BindOccupationListFragment.MediaMetadataCompat)) {
                return onBoardingTutorialActivity5;
            }
            FragmentBuilder_BindRegalQuestionnaireFragment fragmentBuilder_BindRegalQuestionnaireFragment3 = r0;
            FragmentBuilder_BindRegalQuestionnaireFragment fragmentBuilder_BindRegalQuestionnaireFragment4 = new FragmentBuilder_BindRegalQuestionnaireFragment((byte) 0);
            return OnBoardingTutorialActivity.read(onBoardingTutorialActivity5, (FragmentBuilder_BindOnboardingSuccessFragment) null, false, (EasycashCardInfoCaseModule) null, (ReviewInfoCase$JobIncomeDangerousException) null, (FragmentBuilder_BindPurchaseCcSofInputFragment) null, (FragmentBuilder_BindSetDetailFragment) null, (FragmentBuilder_BindHmlOutcomeCounterOfferFragment) null, (FragmentBuilder_BindHmlNtbOutcomeCounterOfferFragment) null, (FragmentBuilder_BindMileageRedemptionSlipFragment) null, (FragmentBuilder_BindTodayTransactionsTabFragment) null, (FragmentBuilder_RegistrationAccountsFragment) null, (FragmentBuilder_BindMwShopAddressStandAloneFragment) null, (FragmentBuilder_BindPrepaidSuccessfulActivationFragment) null, (FragmentBuilder_BindTransferTargetTabFragment) null, (FragmentBuilder_BindPromptPayTargetSelectFragment) null, (FragmentBuilder_BindTabDebitCardServiceFragment) null, (FragmentBuilder_BindWifiSettingsFragment) null, (FragmentBuilder_BindPointTabFragment) null, (EasycashSummaryCaseModule) null, (FragmentBuilder_BindStopChequeHistoryFragment) null, (FragmentBuilder_BindRemittanceRecipientDetailFragment) null, (FragmentBuilder_BindSmeLoanFragment) null, fragmentBuilder_BindRegalQuestionnaireFragment3, 4194303);
        }
    }
}
