package p040o;

/* renamed from: o.setFlat */
public enum setFlat {
    TRANSFER_FROM,
    TRANSFER_TO,
    TOP_UP,
    BILL_PAYMENT,
    QUICK_PROMPT_PAY,
    QUICK_BALANCE,
    CARDLESS_ATM,
    CHEQUE_STATUS_RECEIVED,
    CHEQUE_STATUS_ISSUED,
    LOAN_PAYMENT,
    STOP_CHEQUE_STATUS,
    E_DONATION,
    ACTIVATE_ORDER_CHEQUE,
    BOND,
    ETB_SET_ACCOUNT_DETAIL_SOURCE,
    ETB_SET_ACCOUNT_DETAIL_MAIN,
    FAST_PAY,
    EXPORT_STATEMENT,
    DEEJUNG_TRANSFER,
    DEBIT_CARD,
    CLOSE_ACCOUNT_TARGET,
    DIRECT_DEBIT_SOURCE
}
